//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesos
    {
        public long acc_id { get; set; }
        public long acc_menu_acceso { get; set; }
        public long acc_usuario { get; set; }
        public int acc_permiso { get; set; }
    
        public virtual privilegios_usuario privilegios_usuario { get; set; }
        public virtual submenu_sistema submenu_sistema { get; set; }
    }
}
