//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avales
    {
        public long ava_id { get; set; }
        public string ava_nombre { get; set; }
        public string ava_apellidos { get; set; }
        public string ava_telefono { get; set; }
        public string ava_domicilio { get; set; }
        public string ava_movil { get; set; }
        public bool ava_socio { get; set; }
        public Nullable<long> ava_idsocio { get; set; }
        public long ava_asociado { get; set; }
    
        public virtual asociados asociados { get; set; }
    }
}
