//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_sesiones
    {
        public long con_id { get; set; }
        public string con_usuario { get; set; }
        public string con_computadora { get; set; }
        public Nullable<System.DateTime> con_fecha_sesion { get; set; }
    }
}
