//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados
    {
        public estados()
        {
            this.asociados = new HashSet<asociados>();
            this.municipios = new HashSet<municipios>();
            this.personal = new HashSet<personal>();
        }
    
        public long est_id { get; set; }
        public string est_nombreestado { get; set; }
    
        public virtual ICollection<asociados> asociados { get; set; }
        public virtual ICollection<municipios> municipios { get; set; }
        public virtual ICollection<personal> personal { get; set; }
    }
}
