//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class identificacion
    {
        public long ide_id { get; set; }
        public string ide_lado { get; set; }
        public byte[] ide_identificacion { get; set; }
        public long ide_asociado { get; set; }
    
        public virtual asociados asociados { get; set; }
    }
}
