//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidades
    {
        public localidades()
        {
            this.asociados = new HashSet<asociados>();
            this.colonias = new HashSet<colonias>();
            this.personal = new HashSet<personal>();
        }
    
        public long loc_id { get; set; }
        public string loc_nombrelocalidad { get; set; }
        public long loc_municipio { get; set; }
    
        public virtual ICollection<asociados> asociados { get; set; }
        public virtual ICollection<colonias> colonias { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual ICollection<personal> personal { get; set; }
    }
}
