//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_sesiones
    {
        public long log_id { get; set; }
        public string log_usuario { get; set; }
        public string log_computadora { get; set; }
        public Nullable<System.DateTime> log_fecha_sesion { get; set; }
        public string log_accion { get; set; }
    }
}
