//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_sistema
    {
        public menu_sistema()
        {
            this.submenu_sistema = new HashSet<submenu_sistema>();
        }
    
        public long men_id { get; set; }
        public string men_nombre { get; set; }
    
        public virtual ICollection<submenu_sistema> submenu_sistema { get; set; }
    }
}
