//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public municipios()
        {
            this.asociados = new HashSet<asociados>();
            this.localidades = new HashSet<localidades>();
            this.personal = new HashSet<personal>();
        }
    
        public long mun_id { get; set; }
        public string mun_nombremunicipio { get; set; }
        public long mun_estado { get; set; }
    
        public virtual ICollection<asociados> asociados { get; set; }
        public virtual estados estados { get; set; }
        public virtual ICollection<localidades> localidades { get; set; }
        public virtual ICollection<personal> personal { get; set; }
    }
}
