//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones
    {
        public operaciones()
        {
            this.transacciones = new HashSet<transacciones>();
        }
    
        public long ope_id { get; set; }
        public System.DateTime ope_fecha { get; set; }
        public System.DateTime ope_hora { get; set; }
    
        public virtual ICollection<transacciones> transacciones { get; set; }
    }
}
