//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public personal()
        {
            this.fotospersonal = new HashSet<fotospersonal>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public long per_id { get; set; }
        public string per_nombre { get; set; }
        public string per_apellidos { get; set; }
        public string per_sexo { get; set; }
        public System.DateTime per_fechanacimiento { get; set; }
        public string per_estadocivil { get; set; }
        public long per_estado { get; set; }
        public long per_municipio { get; set; }
        public long per_localidad { get; set; }
        public long per_colonia { get; set; }
        public int per_codigopostal { get; set; }
        public string per_domicilio { get; set; }
        public string per_telefono { get; set; }
        public string per_correoelectronico { get; set; }
        public string per_movil { get; set; }
    
        public virtual colonias colonias { get; set; }
        public virtual estados estados { get; set; }
        public virtual ICollection<fotospersonal> fotospersonal { get; set; }
        public virtual localidades localidades { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
