//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilegios_usuario
    {
        public privilegios_usuario()
        {
            this.accesos = new HashSet<accesos>();
        }
    
        public long pri_id { get; set; }
        public string pri_nombre { get; set; }
        public string pri_descripcion { get; set; }
    
        public virtual ICollection<accesos> accesos { get; set; }
    }
}
