//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submenu_sistema
    {
        public submenu_sistema()
        {
            this.accesos = new HashSet<accesos>();
        }
    
        public long sub_id { get; set; }
        public string sub_nombre { get; set; }
        public long sub_menu { get; set; }
    
        public virtual ICollection<accesos> accesos { get; set; }
        public virtual menu_sistema menu_sistema { get; set; }
    }
}
