//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacciones
    {
        public long tra_id { get; set; }
        public System.DateTime tra_fecha { get; set; }
        public decimal tra_subtotal { get; set; }
        public decimal tra_interes { get; set; }
        public decimal tra_total { get; set; }
        public long tra_pago { get; set; }
        public long tra_operacion { get; set; }
    
        public virtual operaciones operaciones { get; set; }
        public virtual pagos pagos { get; set; }
    }
}
