//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public long usu_id { get; set; }
        public string usu_usuario { get; set; }
        public string usu_contrasena { get; set; }
        public string usu_cargo { get; set; }
        public string usu_estadocuenta { get; set; }
        public long usu_personal { get; set; }
    
        public virtual personal personal { get; set; }
    }
}
