//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_contabilidad_entrada
    {
        public long con_id { get; set; }
        public string con_concepto { get; set; }
        public decimal con_monto { get; set; }
        public decimal con_interes { get; set; }
        public decimal con_total { get; set; }
        public System.DateTime con_fecha { get; set; }
        public string con_operacion { get; set; }
        public Nullable<int> con_operador { get; set; }
    }
}
