//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_colonias
    {
        public long col_id { get; set; }
        public string col_nombrecolonia { get; set; }
        public long col_localidad { get; set; }
        public long loc_id { get; set; }
        public string loc_nombrelocalidad { get; set; }
        public long loc_municipio { get; set; }
        public long mun_id { get; set; }
        public string mun_nombremunicipio { get; set; }
        public long mun_estado { get; set; }
        public long est_id { get; set; }
        public string est_nombreestado { get; set; }
    }
}
