//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_personal
    {
        public long per_id { get; set; }
        public string per_nombre { get; set; }
        public string per_apellidos { get; set; }
        public int per_codigopostal { get; set; }
        public long per_colonia { get; set; }
        public string per_correoelectronico { get; set; }
        public string per_domicilio { get; set; }
        public string per_estadocivil { get; set; }
        public System.DateTime per_fechanacimiento { get; set; }
        public string per_movil { get; set; }
        public string per_sexo { get; set; }
        public string per_telefono { get; set; }
        public string est_nombreestado { get; set; }
        public string mun_nombremunicipio { get; set; }
        public string loc_nombrelocalidad { get; set; }
        public string col_nombrecolonia { get; set; }
        public byte[] fot_fotoperfil { get; set; }
    }
}
