//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_socios_adeudo
    {
        public long aso_id { get; set; }
        public string aso_nombre { get; set; }
        public string aso_domicilio { get; set; }
        public Nullable<decimal> pag_pagar { get; set; }
        public Nullable<System.DateTime> pag_fechapago { get; set; }
    }
}
