//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rep_usuarios
    {
        public long per_id { get; set; }
        public string usu_usuario { get; set; }
        public string usu_cargo { get; set; }
        public string usu_estadocuenta { get; set; }
        public string per_nombre { get; set; }
        public string per_apellidos { get; set; }
        public string per_telefono { get; set; }
        public string per_movil { get; set; }
        public string per_correoelectronico { get; set; }
    }
}
